import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./reset.css";
import "./global.css";
import { ResultsContextProvider } from "./context/resultsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chifoumi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ResultsContextProvider>
        <body className={inter.className}>{children}</body>
      </ResultsContextProvider>
    </html>
  );
}
